# Generated by Django 5.0.3 on 2024-03-05 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pay', '0004_discount_tax_alter_item_price_order_discount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='payment_intent_client_secret',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Клиентский секрет платежного интента'),
        ),
        migrations.AddField(
            model_name='item',
            name='payment_intent_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ID платежного интента'),
        ),
    ]
