# Generated by Django 5.0.3 on 2024-03-06 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pay', '0005_item_payment_intent_client_secret_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tax',
            options={'verbose_name': 'Налог', 'verbose_name_plural': 'Налоги'},
        ),
        migrations.RemoveField(
            model_name='item',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='item',
            name='payment_intent_client_secret',
        ),
        migrations.RemoveField(
            model_name='item',
            name='payment_intent_id',
        ),
        migrations.RemoveField(
            model_name='tax',
            name='rate',
        ),
        migrations.AddField(
            model_name='tax',
            name='percentage',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=3, verbose_name='Процент'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tax',
            name='tax_rate_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='tax',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
    ]
