# Generated by Django 5.0.3 on 2024-03-06 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pay', '0006_alter_tax_options_remove_item_currency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tax',
            name='inclusive',
            field=models.BooleanField(default=1, verbose_name='Включен в стоимость'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tax',
            name='percentage',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Процент'),
        ),
    ]
