# Generated by Django 5.0.3 on 2024-03-06 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pay', '0007_tax_inclusive_alter_tax_percentage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='taxes',
        ),
        migrations.AddField(
            model_name='order',
            name='taxes',
            field=models.ManyToManyField(blank=True, null=True, to='pay.tax'),
        ),
    ]
