# Generated by Django 5.0.3 on 2024-03-06 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pay', '0008_remove_order_taxes_order_taxes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='discount',
            options={'verbose_name': 'Налог', 'verbose_name_plural': 'Налоги'},
        ),
        migrations.AddField(
            model_name='discount',
            name='coupon_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='discount',
            name='percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Скидка в процентах'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='Скидка'),
        ),
        migrations.AlterField(
            model_name='order',
            name='taxes',
            field=models.ManyToManyField(blank=True, to='pay.tax', verbose_name='Налоги'),
        ),
    ]
