# Generated by Django 5.0.3 on 2024-03-06 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pay', '0009_alter_discount_options_discount_coupon_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='discount',
            options={'verbose_name': 'Скидка', 'verbose_name_plural': 'Скидки'},
        ),
        migrations.RemoveField(
            model_name='discount',
            name='amount',
        ),
        migrations.AlterField(
            model_name='discount',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='percent',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Скидка в процентах'),
        ),
    ]
